<ul class="nav">
<?php 

foreach ($this->container as $page) { 
  $isActive = $page->isActive(false);
  $liClass = $isActive ? ' class="active dropdown"' : ' class="dropdown"';
?>
  <li<?php echo $liClass; ?>>
    <a href="<?php if ($page->hasPages()) { ?>#<?php } else { echo $page->getHref(); } ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $page->getLabel(); ?><?php if ($page->hasPages()) { ?> <b class="caret"></b><?php } ?></a>
  <?php if ($page->hasPages()) { ?>
    <ul class="dropdown-menu">
    <?php 
    foreach ($page as $page) {
      $isActive2 = $page->isActive(true);
      $liClass2 = $isActive2 ? ' class="active"' : '';
    ?>
      <li<?php echo $liClass2; ?>><?php echo $this->menu()->htmlify($page); ?></li>
    <?php } ?>
  </ul>
  <?php } ?>
    </li>
<?php } ?>
</ul>