<?php
$session = array(
    array(
        'controller' => $this->controller,
        'label' => $this->pageTitle
    )
);
?>

<?php echo $this->partial('partial/pageheader.phtml', array('controller' => $this->pageTitle, 'action' => $this->pageTitleNew)); ?>
<?php echo $this->partial('partial/breadcrumb.phtml', array('session' => $session, 'action' => $this->pageTitleNew)); ?>

<div class="row">
    <?php echo $this->partial('partial/sub-navigation.phtml'); ?>

    <div class="span10">

        <div class="row">
            <div class="span10">
                <form action="<?php echo $this->url(array('module' => 'admin', 'controller' => $this->controller, 'action' => 'new'), NULL, true); ?>" method="post" class="form-horizontal well" enctype="multipart/form-data">
                    <fieldset>
                        <div class="control-group">
                            <label class="control-label" for="categoria">Categoria Pai</label>
                            <div class="controls">
                                <select id="categoria" name="categoria">
                                    <option value="">Selecione uma categoria</option>
                                    <?php
                                    foreach ($this->categorias as $id => $categoria) :
                                        ?>
                                        <option value="<?php echo $id ?>"><?php echo $categoria; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="estabelecimento">Estabelecimeto</label>
                            <div class="controls">
                                <select id="categoria" name="estabelecimento">
                                    <option value="">Selecione um estabelecimento</option>
                                    <?php
                                    foreach ($this->estabelecimentos as $id => $nome) :
                                        ?>
                                        <option value="<?php echo $id ?>"><?php echo $nome; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="titulo">Título</label>
                            <div class="controls">
                                <input type="text" class="input-xlarge" id="titulo" name="titulo">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="descricao">Descrição</label>
                            <div class="controls">
                                <textarea class="input-xlarge" id="descricao" name="descricao"></textarea>
                            </div>
                        </div> 
                        <div class="control-group">
                            <label class="control-label" for="valor">Valor</label>
                            <div class="controls">
                                <input type="text" class="input-medium" id="valor" name="valor">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="imagem">Imagem</label>
                            <div class="controls">
                                <input type="file" id="imagem" name="imagem" class="span5" />
                            </div>
                        </div>

                        <?php echo $this->partial('partial/form_actions.phtml'); ?>
                    </fieldset>
                </form>
            </div>
        </div>

    </div>
</div>