<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Administração - Mande-me</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl() .'/assets/css/bootstrap.css'); ?>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl() .'/assets/css/bootstrap-responsive.css'); ?>
    <script src="<?php echo $this->baseUrl() . '/assets/js/modernizr-2.0.6.min.js'; ?>"></script>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->baseUrl(); ?>/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl(); ?>/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl(); ?>/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl(); ?>/assets/ico/apple-touch-icon-57-precomposed.png">

    <script type="text/javascript"> var base_url = '<?php echo $this->baseUrl(); ?>'; </script>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url( array('module' => 'admin', 'controller' => 'index', 'action' => 'dashboard'), NULL, true ); ?>">Mande-me</a>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <?php echo $this->userSession->nome; ?>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">Perfil</a></li>
              <li class="divider"></li>
              <li><a href="<?php echo $this->url( array('module' => 'admin', 'controller' => 'auth', 'action' => 'logout'), NULL, true ); ?>">Sair</a></li>
            </ul>
          </div>
          <div class="nav-collapse">
            <?php
            $this->navigation()->menu()->setPartial(array('partial/navigation.phtml', 'admin'));
            echo $this->navigation()->menu()->render();
            ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->layout()->content; ?>

    </div> <!-- /container -->

    <div id="deleteConfirm" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Confirmar Exlusão!!</h3>
      </div>
      <div class="modal-body">

        <p>Você tem certeza que deseja excluir este item?</p>

      </div>
      <div class="modal-footer">
        <a href="javascript: void(0);" onClick="javascript: $('#deleteConfirm').modal('hide');" class="btn" data-dismiss="modal" >Cancelar</a>
        <a href="javascript: void(0);" class="btn btn-primary bt-confirmar">Confirmar</a>
      </div>
    </div>

    <div id="modalConfirmation" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>Confirmar Operação!!</h3>
      </div>
      <div class="modal-body">

        <p>Você tem certeza que deseja salvar este item?</p>

      </div>
      <div class="modal-footer">
        <a href="javascript: void(0);" onClick="javascript: $('#deleteConfirm').modal('hide');" class="btn" data-dismiss="modal" >Cancelar</a>
        <a href="javascript: void(0);" class="btn btn-primary bt-confirmar">Confirmar</a>
      </div>
    </div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <?php 
    echo $this->headScript()->appendFile($this->baseUrl() . "/assets/ckeditor/ckeditor.js")
        ->headScript()->appendFile($this->baseUrl() . "/assets/ckeditor/adapters/jquery.js");


    echo '<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>';
    echo '<script type="text/javascript" src="'.$this->baseUrl().'/public/plupload/js/plupload.full.js"></script>';

    echo $this->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-transition.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-alert.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-modal.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-dropdown.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-tab.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-tooltip.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-popover.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-button.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-collapse.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-carousel.js")
    	 ->headScript()->appendFile($this->baseUrl() . "/assets/js/bootstrap-typeahead.js")
       ->headScript()->appendFile($this->baseUrl() . "/js/mylibs/jquery.form.js")
       ->headScript()->appendFile($this->baseUrl() . "/js/mylibs/jquery.maskedinput-1.3.min.js")
       ->headScript()->appendFile($this->baseUrl() . "/js/mylibs/jquery.maskMoney.min.js")
       ->headScript()->appendFile($this->baseUrl() . "/js/mylibs/jquery.metadata.js")
       ->headScript()->appendFile($this->baseUrl() . "/js/mylibs/jquery.validate.min.js")
       ->headScript()->appendFile($this->baseUrl() . "/assets/js/application.js");
    ?>

  </body>
</html>